### ISSUE TITLE
Font issue when printing with ocgcolorlinks

### ISSUE THREAD

**Issue by chrmatt** [agrahn/ocgx2#1]
The printed text of links when using ocgcolorlinks has inferior quality than ordinary text. A minimal example is:
```
\documentclass{article}
\usepackage{hyperref}
\usepackage[ocgcolorlinks]{ocgx2}

\begin{document}
Visit \href{https://ctan.org/tex-archive/macros/latex/contrib/ocgx2}{ocgx2 ocgx2 ocgx2}.
\end{document}
```

To make the quality issue visible, I printed the resulting PDF in Adobe Acrobat Reader DC with Microsoft print to PDF on Windows 10. Zooming in on the resulting PDF reveals the following:
![image](https://user-images.githubusercontent.com/14225244/26842979-f1c7333c-4aee-11e7-8afc-a49a7691cd19.png)

The same issue exists when using an ordinary printer (of course with a limited effect without a magnifier, but the difference to normal text is visible).

**Comment by agrahn** [comment]
My tests in Evince and AR-9 for Linux didn't produce the rendering issue you reported. Did you test with the current package version? I have TeXLive-2017 here.

**Comment by chrmatt** [comment]
I have MiKTeX with everything updated, ocgx is version 0.29. The same happens when printing with Foxit Reader. I don't have a recent version of Evince here, but I've attached the original PDF and the log file from the compilation.

[font.pdf](https://github.com/agrahn/ocgx2/files/1067451/font.pdf)
[font.log.txt](https://github.com/agrahn/ocgx2/files/1067462/font.log.txt)

**Comment by agrahn** [comment]
font.pdf looks ok for me, even at 6400% zoom in AR.

Started out to look for a Windows box, installed MiKTeX portable, synchronized the package database, updated all packages, ran the example, opened the PDF in Foxit, zoomed to 3200%. The same result here. The PDF renders as expected.

**Comment by chrmatt** [comment]
The issue occurs after *printing* the PDF, the original file is also fine on my machine. The picture in my first post was obtained by printing the PDF to a file (thus ocgx2 is black as intended).

**Comment by agrahn** [comment]
This I tested too. I printed your font.pdf to a Postscript file and looked at it in GV, twice zoomed 64 times onto the curved "o". The contour is well rendered like a vector graphics curve.

zoom=1:

![font_printed_to_ps_zoom_1](https://user-images.githubusercontent.com/832385/27027490-f6664d5c-4f61-11e7-8755-ffce8261ec42.png)

zoom=64x64=4096:

![font_printed_to_ps_zoom_4096](https://user-images.githubusercontent.com/832385/27027501-fc6bda32-4f61-11e7-845d-cb446fc2e3b7.png)

**Comment by chrmatt** [comment]
Then it seems to be an issue with the printing. I've attached the output obtained by using Microsoft Print to PDF in Adobe Reader.
[printed.pdf](https://github.com/agrahn/ocgx2/files/1067669/printed.pdf)

Maybe postscript printers handle this differently?

**Comment by agrahn** [comment]
Indeed, printed.pdf looks very funny. This should be reported to Microsoft, if possible.

It is really strange that the printer driver you are using stumbles across this, because the `ocgcolorlinks` implementation of `ocgx2` puts the glyph outlines only once into the PDF file and just fills them with different colours for viewing and for printing.

**Comment by chrmatt** [comment]
Apparently Microsoft's driver does something weird. I've tried a postscript printer on Windows and there everything is fine. However, the reason I reported this here in the first place is that this issue does *not* occur with the following code:
```
\documentclass{article}
\usepackage[ocgcolorlinks]{hyperref}

\begin{document}
Visit \href{https://ctan.org/tex-archive/macros/latex/contrib/ocgx2}{ocgx2 ocgx2 ocgx2}.
\end{document}
```

Hence, ocgx2 must do something to trigger this weird behavior...

**Comment by agrahn** [comment]
Unlike the `ocgx2` implementation, `hyperref`'s `ocgcolorlinks` implementation writes the link text **twice** into the output PDF, each with a different colour. But this approach does not allow the link text to be broken about line breaks (because the text must be put into `\savebox`es for being output twice. Saveboxes don't allow line breaks). Breakable link text was the main motivation for the `ocgx2` implementation of `ocgcolorlinks`. This produces advanced, yet valid PDF code which seems to be beyond Microsoft's driver.

**Comment by chrmatt** [comment]
Sounds like it cannot be fixed then. However, it seems this is not a Microsoft specific issue: When I use a physical printer, the output also looks strange. Also, the following postscript file was produced by printing to a file in Adobe Reader on Red Hat Linux:
[font.zip](https://github.com/agrahn/ocgx2/files/1068253/font.zip)

When I convert this to PDF using ps2pdf, the output is perfect; when I open the ps directly in (an outdated version of) evince, the quality is bad. So it seems, it sometimes works well, sometimes it does not...

**Comment by agrahn** [comment]
Printing from AR-9 (Linux) into a PS file is what I did for my 3rd comment, which looks ok in GV and printed on paper. Also, your font.ps looks ok in GV, if zoomed onto a curved contour. No steps visible which are bigger than the pixel rows of my screen.
