### ISSUE TITLE
links do not deactivate when their layer is turned invisible

### ISSUE THREAD

**Issue by it-eddy** [agrahn/ocgx2#2]
After turning a ocg layer invisible the link borders are still visible and the link is still active and clickable.

Minimal sample for reproduction:
```
\documentclass[10pt,a4paper]{article}
\usepackage{hyperref}
\usepackage{ocgx2}
\begin{document}
permanent text

\begin{ocg}{linkLayer}{linkLayer}{0}
\href{https://web.de}{https://web.de}
\end{ocg}

\end{document}
```
![clickable_invisible_link_with_borders](https://user-images.githubusercontent.com/20926136/27143278-225122a2-512e-11e7-958a-c25d09fcb234.jpg)

**Comment by agrahn** [comment]
`hyperref` is not aware of any OCG-making package except its own `ocgcolorlinks` implementation (which breaks everything).

You will have to patch `hyperref` internals, as shown below for the `\hyper@linkurl` macro. The code makes use of the `\pbs_pdflink:nn` command provided by the `pdfbase.sty` file loaded by `ocgx2`:

```latex
\documentclass[10pt,a4paper]{article}

\usepackage{hyperref}
\usepackage{ocgx2}
%\usepackage[ocgcolorlinks]{ocgx2}

\makeatletter
\ExplSyntaxOn
  \let\pbs@pdflink\pbs_pdflink:nn
  \let\g@ocgxii@patch@tl\g_ocgxii_patch_tl %link border linewidth patch for dvips+ps2pdf
\ExplSyntaxOff

%patch hyperref's internals
\def\hyper@linkurl#1#2{%
  \begingroup%
    \Hy@pstringdef\Hy@pstringURI{#2}%
    \hyper@chars%
    \leavevmode%
    \pbs@pdflink{
      \Hy@setpdfborder\g@ocgxii@patch@tl
      \ifx\@pdfhightlight\@empty
      \else
        /H\@pdfhighlight
      \fi
      \ifx\@urlbordercolor\relax
      \else
        /C[\@urlbordercolor]%
      \fi
      /Subtype/Link%
      \ifHy@pdfa /F 4\fi
      /A<<%
        /Type/Action%
        /S/URI%
        /URI(\Hy@pstringURI)%
        \ifHy@href@ismap
          /IsMap true%
        \fi
        \Hy@href@nextactionraw
      >>%
    }{%
    \Hy@colorlink\@urlcolor#1\Hy@xspace@end%
    \Hy@endcolorlink}%
  \endgroup%
}

\makeatother


\begin{document}
permanent text

\begin{ocg}{linkLayer}{linkLayer}{0}
  \href{https://web.de}{https://web.de}
\end{ocg}

\end{document}
```

**Comment by it-eddy** [comment]
Unfortunately your patch does not work for me. I get 2 compile errors:
```
! Undefined control sequence.
\hyper@linkurl ...@chars \leavevmode \pbs@pdflink
{ \Hy@setpdfborder \g@ocgx...
l.53 \href{https://web.de}{https://web.de}
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
! Undefined control sequence.
\hyper@linkurl ...setpdfborder \g@ocgxii@patch@tl
\ifx \@pdfhightlight \@emp...
l.53 \href{https://web.de}{https://web.de}
```
Right now I am using mainly the XeLaTex from livetex 2014 running on Windows 8.1, but even with the new XeLaTex from livetex 2017 on Ubuntu 17 I get at least the second error.

**Comment by agrahn** [comment]
No error here with TL-2017 on Linux, pkgs updated yesterday. See attached example pdf (`xelatex`-generated).

[linkOnLayer.zip](https://github.com/agrahn/ocgx2/files/1087264/linkOnLayer.zip)

Or, open on [**ShareLaTeX**](https://www.sharelatex.com/project/5948c4a68920e4376fb8f671)

In any case, you should update the TeX installation, preferably to TeXLive-2017 (available for many platforms, including Windows) and update all packages using its package manager.
