### ISSUE TITLE
"Control sequence \toggleocgs already defined." error message when loading `\usetikzlibrary{ocgx}` in advance

### ISSUE THREAD

**Issue by Mo-Gul** [agrahn/ocgx2#5]
Today I TeXed a document again which worked fine in December 2016. Now the MWE

```
\documentclass{standalone}
%% loading the package here just raises the same error somewhere else
%\usepackage{ocgx2}
\usepackage{tikz}
    \usetikzlibrary{ocgx}
\usepackage{ocgx2}
\begin{document}
    test
\end{document}
```

raises the error message

> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> ! LaTeX error: "kernel/command-already-defined"
> ! Control sequence \toggleocgs already defined.
> ! See the LaTeX3 documentation for further information.
> ! For immediate help type H <return>.
> !...............................................  
>                                                   
> l.576 \cs_new:Npn\toggleocgs
>                           {\switchocg*}

Is that a bug of your or the other package?

**Comment by agrahn** [comment]
`ocgx2` is a replacement for `ocgx`. Both packages cannot be used in the same document. In order to load TikZ styles, you need:

```latex
\documentclass{standalone}

\usepackage{tikz}
\usepackage[tikz]{ocgx2}

\begin{document}
   test
\end{document}
```
See sect. Introduction of [README.md](https://github.com/agrahn/ocgx2/blob/master/README.md#introduction).

**Comment by Mo-Gul** [comment]
Shame on me. Sorry for not "rtfm" and bothering you. You can close this issue, because following the manual works perfectly fine.
