### ISSUE TITLE
Wrong size of clickable link when compiled via XeTeX

### ISSUE THREAD

**Issue by mehrt** [agrahn/ocgx2#6]
I tried to use this package with pdfXeLaTeX, and found that if I open the resulting pdf file, Acrobat reader displays a black box about the size of half the page when the link is clicked. This is not the case when I compile using pdfLaTeX. I also posted a question about it at [tex.se](https://tex.stackexchange.com/q/390861/4888).
Example code:
```
\documentclass{article}
\usepackage[colorlinks=true,linkcolor=blue,urlcolor=blue]{hyperref}
\usepackage[ocgcolorlinks]{ocgx2}
\begin{document}
\tableofcontents
\section{this is a very very very very very very very very very very very very very very very very very very long section}
\end{document}
```
Attached is a pdf compiled with pdfLaTeX and one with pdfXeLaTeX, to show the behaviour.

[toctest.pdflatex.pdf](https://github.com/agrahn/ocgx2/files/1293504/toctest.pdflatex.pdf)
[toctest.pdfxelatex.pdf](https://github.com/agrahn/ocgx2/files/1293505/toctest.pdfxelatex.pdf)

**Comment by mehrt** [comment]
I actually tried to circumvent this by using ...
`\hypersetup{pdfhighlight=/N}`
... but while that switches off the highlight on click for hyperref alone, it doesn't seem to be respected by ocgx2.

**Comment by agrahn** [comment]
Seems rather an (x)dvipdfmx bug. I need to investigate this further.

**Comment by mehrt** [comment]
Thanks a lot.
By the way, it also happens for a short link that doesn't break - it's just that a long link was the case that made me discover this.

**Comment by mehrt** [comment]
Here's what was posted in a comment by tex.se-user diabonas:

_A quick fiddling about with ocgx2.sty seems to suggest to me that ll. 763-767 cause the problem: they create a box of size 2\paperwidthx2\paperheight, which is roughly the wrong link size XeTeX produces. If these lines are removed, the links have the expected size instead. I do not currently understand the purpose of this box, so removing it might have some unexpected consequences that I am not aware of, but it at least seems like a good starting point for a more thorough investigation._

I commented those lines ...
```
%    \vbox_to_zero:n{
%      \vss
%      \hbox_to_zero:n{\skip_horizontal:n{2\paperwidth}.\hss}
%      \skip_vertical:n{2\paperheight}
%    }
```
... and now it looks as if it works as it should. Please check if that's a plausible fix, because neither him nor me seem to understand enough of the code ...

**Comment by agrahn** [comment]
Thank you. I removed those lines for xetex. (See updated oxgx2.sty and ocgbase.sty). I introduced this a while back. Those lines insert a default glyph (period, '.') off the page limits. This prevents empty links, such as `\href{https://ctan.org}{\quad}` from flooding the page with link colour. (See Ben Lerners original implementation of breakable ocgcolorlinks: https://tex.stackexchange.com/q/47267 ) . Ok, this safety measure now only works with pdf/LuaTeX.

**Comment by agrahn** [comment]
A new version is on the way to CTAN. With XeTeX you have to ensure that there are no empty links in the document.

**Comment by mehrt** [comment]
Thanks for the quick fix, and sorry that it causes disabling of a safety feature, I can totally see why you did that ...

**Comment by agrahn** [comment]
So then let's close the issue.

**Comment by agrahn** [comment]
@mehrt : v0.31 ; I found a way to cope with empty link text with `ocgcolorlinks` option for the xetex driver too: An invisibly small downscaled period (".") from the LM OpenType font is put directly after the link text.

**Comment by mehrt** [comment]
Pretty cool ... so works with xetex, without loosing any pre-existing functionality now (or rather, once distributed ;-)).
